### ISSUE TITLE
method timestampvm.proposeBlock does not exist/is not available

### ISSUE THREAD

**Issue by egeaybars123** [ava-labs/timestampvm#41]
I was following through the Avalanche docs to set up my custom VM. I set up a local network (AvalancheGo v.1.9.14), and spinned up a subnet called timestampvm (I forked the timestampvm repository).  The subnet was spinned up successfull with a custom VM with the right VMID. However, whenever I sent a request to one of the nodes, I kept getting the error: 

`
 {"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method timestampvm.proposeBlock does not exist/is not available"}}
`

Any ideas as to why this is happening?

**Comment by hexfusion** [comment]
The current timestampVM does not support 1.9.14 (protocol version 24). A PR[1] was started to make this more current but has not made progress. We would love your help in fixing this if your interested. 

[1] https://github.com/ava-labs/timestampvm/pull/39

**Comment by egeaybars123** [comment]
> The current timestampVM does not support 1.9.14 (protocol version 24). A PR[1] was started to make this more current but has not made progress. We would love your help in fixing this if your interested.
> 
> [1] #39

I would love to. I guess the current supported version is v1.9.7 as I could tell from the shell scripts. Clarifying this in the docs would be good in order not to confuse developers. I will also be starting a PR to update the docs! Thank you for your quick response.

**Comment by egeaybars123** [comment]
I'm closing this issue because I faced this issue due to a misunderstanding in Avalanche docs. Soon, I will make a PR to clarify some points in setting up custom VMs in the docs.
