### ISSUE TITLE
Can't propose block

### ISSUE THREAD

**Issue by sanderpick** [ava-labs/timestampvm#7]
Non-static API calls are not recognized:

```
curl -X POST --data '{
                                   "jsonrpc": "2.0",
                                   "method": "timestampvm.proposeBlock",
                                   "params":{
                                       "data":"SkB92YpWm4Q2iPnLGCuDPZPgUQMxajqQQuz91oi3xD984f8r"
                                   },
                                   "id": 1
                               }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/vm/timestampvm
{"jsonrpc":"2.0","error":{"code":-32000,"message":"rpc: can't find method \"timestampvm.ProposeBlock\"","data":null},"id":1}
```

Static calls work fine:
```
curl -X POST --data '{
                                   "jsonrpc": "2.0",
                                   "method": "timestampvm.encode",
                                   "params":{
                                       "data":"SkB92YpWm4Q2iPnLGCuDPZPgUQMxajqQQuz91oi3xD984f8r"
                                   },
                                   "id": 1
                               }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/vm/timestampvm
{"jsonrpc":"2.0","result":{"bytes":"M2NcATdFX63NpvNFE5pRgLXY1DLgo7oLVNKYNzTVEswz6YEALQ5EvzXeoR6sqzBJhjUo84t","encoding":"cb58"},"id":1}
```

The [tutorial](https://docs.avax.network/build/tutorials/platform/create-a-virtual-machine-vm#api) shows to use an `/ext/bc` address (typo?), but I've tried all the endpoints listed by the node on startup and none recognize the method. From the tutorial:

```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "timestampvm.proposeBlock",
    "params":{
        "data":"SkB92YpWm4Q2iPnLGCuDPZPgUQMxajqQQuz91oi3xD984f8r"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/sw813hGSWH8pdU9uzaYy9fCtYFfY7AjDd2c9rm64SbApnvjmk
```

If that's not a typo, it would help to mention where to find the right endpoint vs. just using a hardcoded value in the sample call, i.e., `sw813hGSWH8pdU9uzaYy9fCtYFfY7AjDd2c9rm64SbApnvjmk`.

**Comment by ceyonur** [comment]
This is not a static API. The `sw813hGSWH8pdU9uzaYy9fCtYFfY7AjDd2c9rm64SbApnvjmk` is blockchain ID, so it can be different on your end. This is the same ID when you create your blockchain with `platform.createBlockchain`. See: [Create Custom Blockchain](https://docs.avax.network/build/tutorials/platform/create-custom-blockchain#create-the-blockchain) .

We're also updating the doc to prevent any confusion about that. Thanks for feedback!

**Comment by sanderpick** [comment]
Got it, that makes sense 👍 

Following the Custom Blockchain tutorial, whenever I create a subnet against a local test net, the P chain seems to crash/go unhealthy with:

```
DEBUG[09-10|15:37:42] avalanchego/health/service.go#95: starting to run P
ERROR[09-10|15:32:43] avalanchego/health/service.go#102: failed to encode "P" when it was failing due to: json: unsupported value: NaN
```

I'll keep poking around and raise the issue in a more appropriate place if needed. Thanks for the help.

**Comment by ceyonur** [comment]
Feel free to join our discord channel in: chat.avalabs.org
